In [42]:
import numpy as np
import scipy
from scipy.stats import norm
from __future__ import division
import pandas
import csv
import matplotlib.pyplot as plt

In [43]:
with open('Medical_data.csv','r') as csv_file:
    csv_reader = list(csv.reader(csv_file,delimiter=","))
    csv_dicReader = csv.DictReader(csv_file)
    my_data = np.array(csv_reader)
    
    input_data = np.array(my_data[1:,1:],dtype=np.float)
    tag_data = np.array(my_data[1:, 0],dtype=np.string_)

In [44]:
n = input_data.shape[0]
dimension = input_data.shape[1]
print(n)
print(dimension)

3000
3


In [51]:
tag0 = 0
tag1 = 0
tag2 = 0
in0 = 0
in1 = 0
in2 = 0
tag0_data = np.zeros((1000, 3))
tag1_data = np.zeros((1000, 3))
tag2_data = np.zeros((1000, 3))
for i in range(0, n):
    if tag_data[i] == b'HEALTHY':
        tag0_data[in0] = input_data[i]
        in0 += 1
    elif tag_data[i] == b'MEDICATION':
        tag1_data[in1] = input_data[i]
        in1 += 1
    else:
        tag2_data[in2] = input_data[i]
        in2 += 1
print(np.amax(tag0_data, axis=0))
print(np.amin(tag0_data, axis=0))
print(np.amax(tag1_data, axis=0))
print(np.amin(tag1_data, axis=0))
print(np.amax(tag2_data, axis=0))
print(np.amin(tag2_data, axis=0))

[ 4.52943508  0.68722268  4.28072058]
[-1.60594029 -0.70715607 -1.31089881]
[ 4.58908949  5.14835187  0.78020348]
[-1.47416227 -1.86650982 -0.69548506]
[ 0.62816343  4.61835321  5.09885427]
[-0.67092477 -1.54539822 -1.72092974]


In [79]:
data_bins = np.arange(-1.9, 5.2, 0.1)
#print(data_bins)
#print(tag0_data[:, 0])

In [89]:
plt.hist(tag0_data[:, 0], bins=data_bins)
plt.show()

In [90]:
plt.hist(tag0_data[:, 1], bins=data_bins)
plt.show()

In [91]:
plt.hist(tag0_data[:, 2], bins=data_bins)
plt.show()

In [92]:
plt.hist(tag1_data[:, 0], bins=data_bins)
plt.show()

In [93]:
plt.hist(tag1_data[:, 1], bins=data_bins)
plt.show()

In [94]:
plt.hist(tag1_data[:, 2], bins=data_bins)
plt.show()

In [95]:
plt.hist(tag2_data[:, 0], bins=data_bins)
plt.show()

In [96]:
plt.hist(tag2_data[:, 1], bins=data_bins)
plt.show()

In [97]:
plt.hist(tag2_data[:, 2], bins=data_bins)
plt.show()